% initialize contrast bars
function [hAxis] = addContrastBar(hFig, hPanel)

data = guidata(hFig);
if isfield(data, 'hAxis')
    hAxis = data.hAxis;
end

hAxis.contrast1 = axes('Parent',                   hPanel, ...
                                    'Units',                    'normalized', ...
                                    'HandleVisibility',     'callback', ...
                                    'Position',                 [0 0 0.5 1]);

X = zeros(1, 4);
Y = X;
area(hAxis.contrast1, X, Y, ...
                                'FaceColor', [1 1 1],...
                                'Tag', 'Hist');
F = [1 2 3 4];
patch(hAxis.contrast1, 'Faces', F,...
                                  'Vertices', [X' Y'],  ...
                                  'FaceColor', 'c',...
                                  'FaceAlpha', .2,...
                                  'Tag', 'CenterPatch');

patch(hAxis.contrast1, 'Faces', F,...
                                  'Vertices', [X' Y'],  ...
                                  'FaceColor', 'c',...
                                  'FaceAlpha', 1,...
                                  'Tag', 'LeftPatch');

patch(hAxis.contrast1, 'Faces', F,...
                                  'Vertices', [X' Y'],  ...
                                  'FaceColor', 'c',...
                                  'FaceAlpha', 1,...
                                  'Tag', 'RightPatch');

% make contrast bars vertical
set(hAxis.contrast1,'ydir','reverse')
view(hAxis.contrast1, [-90 90])

axis(hAxis.contrast1, 'off')
set(hAxis.contrast1, 'visible', 'off')

hAxis.contrast2 = axes('Parent',                   hPanel, ...
                                    'Units',                    'normalized', ...
                                    'HandleVisibility',     'callback', ...
                                    'Position',                 [0.5 0 0.5 1]);
area(hAxis.contrast2, X, Y, ...
                                'FaceColor', [1 1 1],...
                                'Tag', 'Hist');
patch(hAxis.contrast2, 'Faces', F,...
                                  'Vertices', [X' Y'],  ...
                                  'FaceColor', 'g',...
                                  'FaceAlpha', .2,...
                                  'Tag', 'CenterPatch');

patch(hAxis.contrast2, 'Faces', F,...
                                  'Vertices', [X' Y'],  ...
                                  'FaceColor', 'g',...
                                  'FaceAlpha', 1,...
                                  'Tag', 'LeftPatch');

patch(hAxis.contrast2, 'Faces', F,...
                                  'Vertices', [X' Y'],  ...
                                  'FaceColor', 'g',...
                                  'FaceAlpha', 1,...
                                  'Tag', 'RightPatch');
axis(hAxis.contrast2, 'off')
set(hAxis.contrast2, 'visible', 'off')