function [hMenu, hMenuItem] = addManu(hFig_main)

hMenu.File = uimenu('Parent',                   hFig_main,...
                                'HandleVisibility',      'callback', ...
                                'Label',                     'File');
                    
hMenuItem.Patient  =   uimenu('Parent',             hMenu.File,...
                                                'Label',                'Patient List',...
                                                'Checked',           'off',...
                                                'HandleVisibility', 'callback', ...
                                                'Callback',            @hMenuItem_Patient_Callback);

hMenuItem.Close  =  uimenu('Parent',                 hMenu.File,...
                                              'Label',                   'Close',...
                                              'Separator',            'off',...
                                              'HandleVisibility',    'callback', ...
                                              'Callback',              @hMenuItem_Close_Callback);

% View
hMenu.View = uimenu('Parent',                   hFig_main,...
                                    'HandleVisibility',      'callback', ...
                                    'Label',                     'View');

hMenuItem.CT  =   uimenu('Parent',               hMenu.View,...
                                            'Label',                'Planning',...
                                                'Checked',           'off',...
                                                 'Enable',               'off', ...
                                           'HandleVisibility', 'callback', ...
                                            'Callback',            @hMenuItem_CT_Callback);

hMenuItem.CB  =   uimenu('Parent',               hMenu.View,...
                                            'Label',                'Localization',...
                                                'Checked',           'off',...
                                                 'Enable',               'off', ...
                                           'HandleVisibility', 'callback', ...
                                            'Callback',            @hMenuItem_CB_Callback);

hMenuItem.CTCB  =   uimenu('Parent',               hMenu.View,...
                                                'Label',                'Overlay',...
                                                 'Checked',           'off',...
                                                'Enable',               'off', ...
                                               'HandleVisibility', 'callback', ...
                                                'Callback',            @hMenuItem_CTCB_Callback);

hMenuItem.SS  =   uimenu('Parent',               hMenu.View,...
                                            'Label',                'Structure Set',...
                                                'Checked',           'off',...
                                                'Enable',               'off', ...
                                                'Separator',          'on', ...
                                            'HandleVisibility', 'callback', ...
                                            'Callback',            @hMenuItem_SS_Callback);

hMenuItem.CBDate  =   uimenu('Parent',               hMenu.View,...
                                            'Label',                'CB Date List',...
                                                'Checked',           'off',...
                                                'Enable',               'off', ...
                                            'HandleVisibility', 'callback', ...
                                            'Callback',            @hMenuItem_CBDate_Callback);

hMenuItem.iso  =   uimenu('Parent',               hMenu.View,...
                                                'Label',                'iso',...
                                                'Enable',               'off', ...
                                                'HandleVisibility', 'callback', ...
                                                'Callback',            @hMenuItem_iso_Callback);

hMenuItem.bar  =   uimenu('Parent',               hMenu.View,...
                                                'Label',                'Contrast Adjust',...
                                                'Enable',               'off', ...
                                                'HandleVisibility', 'callback', ...
                                                'Callback',            @hMenuItem_bar_Callback);

hMenuItem.CrossLine  =   uimenu('Parent',               hMenu.View,...
                                                'Label',                'Cross Line',...
                                                'Enable',               'off', ...
                                                'HandleVisibility', 'callback', ...
                                                'Callback',            @hMenuItem_CrossLine_Callback);

hMenuItem.CBInfo  =   uimenu('Parent',               hMenu.View,...
                                                'Label',                'Cone Beam Info',...
                                                'Enable',               'off', ...
                                                'Separator',          'on', ...
                                                'HandleVisibility', 'callback', ...
                                                'Callback',            @hMenuItem_CBInfo_Callback);
                                            
% % Analysis 
hMenu.Analysis = uimenu('Parent',                   hFig_main,...
                                    'HandleVisibility',      'callback', ...
                                    'Visible', 'off',...
                                    'Label',                     'Analysis_Axis');

hMenuItem.AnalysisZ  =   uimenu('Parent',     hMenu.Analysis,...
                                                'Label',                'CBCB',...
                                                'HandleVisibility', 'callback', ...
                                                 'Enable',               'off', ...
                                               'Callback',            @hMenuItem_AnalysisZ_Callback);
                                            
hMenuItem.AnalysisZ_CBCT  =   uimenu('Parent',     hMenu.Analysis,...
                                                'Label',                'CBCT',...
                                                'HandleVisibility', 'callback', ...
                                                 'Enable',               'off', ...
                                               'Callback',            @hMenuItem_AnalysisZ_CBCT_Callback);

hMenuItem.tumor  =   uimenu('Parent',            hMenu.Analysis,...
                                                'Label',                'Tumor Segmentation',...
                                                'HandleVisibility', 'callback', ...
                                                 'Enable',               'off', ...
                                                'Callback',            @hMenuItem_tumor_Callback);                                            

hMenuItem.jhZ  =   uimenu('Parent',     hMenu.Analysis,...
                                                'Label',                'Joint Histogram',...
                                                 'Enable',               'off', ...
                                               'Callback',            @hMenuItem_jhZ_Callback);
                                           
hMenuItem.miZ  =   uimenu('Parent',     hMenu.Analysis,...
                                                'Label',                'Joint Histogram MI',...
                                                 'Enable',               'off', ...
                                               'Callback',            @hMenuItem_miZ_Callback);