function [hPanel, hTable, hPushbutton, hAxis, hPlotObj, hText, Param] = addPanel(hFig)

%% Table panel
hPanel.Table = uipanel('Parent',                    hFig,...    
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'Position',                  [0 0 0.1 1],...
                                'ForegroundColor',       'white',...
                                'BackgroundColor',       'black', ...
                                'HighlightColor',          'black',...
                                'ShadowColor',            'black');
% Patient list
hTable.PL = uitable('parent', hPanel.Table,...
                                   'Units',                          'normalized', ...
                                   'Position',                      [0 0.05 1 0.95],...
                                   'ForegroundColor',         [1 1 1],...
                                   'BackgroundColor',         [0 0 0],...
                                    'ColumnName',             [],...
                                    'Columnwidth',             {200},...
                                    'ColumnFormat',           {'char'},...
                                    'RowName',                  [],...
                                    'FontSize',                     10, ...
                                    'visible',                      'off', ...
                                    'CellSelectionCallback',  @hTable_PL_Callback);

% Patient info                                
hTable.ptInfo = uitable('parent',                       hPanel.Table,...
                                   'Units',                          'normalized', ...
                                   'Position',                      [0 0.9 1 0.1],...
                                   'ForegroundColor',         [1 1 1],...
                                   'BackgroundColor',         [0 0 0],...
                                    'ColumnName',             [],...
                                    'Columnwidth',             {100},...
                                    'ColumnFormat',           {'char'},...
                                    'RowName',                  {'MRN', 'Name', 'Gender'},...
                                    'FontSize',                     10, ...
                                    'Data',                           {'88888888'; 'John Doe'; 'Male'}, ...
                                    'visible',                      'off');
% Patient selection                              
hPushbutton.ptSelection = uicontrol('parent',   hPanel.Table,...
                                                'Style',    'pushbutton',...
                                                'String',    'Load', ...
                                                'Units',     'normalized', ...
                                                'FontSize', 10, ...
                                               'Position', [0.1 0.01 0.8 0.03],...
                                                'ForegroundColor',         [0 1 0],...
                                                'BackgroundColor',         [0 0 0],...
                                                'Visible', 'off',...
                                                'Callback', @hPushbutton_ptSelection_Callback);
                 
% Structture Table
ColumnName =  [];
RowName = [];

hTable.SS = uitable('parent', hPanel.Table,...
                                           'Units', 'normalized', ...
                                           'Position', [0 0.4 1 0.6],...
                                             'ForegroundColor',         [1 1 1],...
                                            'BackgroundColor',         [0 0 0],...
                                            'ColumnName',               ColumnName,...
                                            'Columnwidth',                {25 175},...
                                            'ColumnFormat',             {'logical', 'char'},...
                                            'ColumnEditable',            [true false], ...
                                            'RowName',                     RowName,...
                                            'FontSize',                       10,....
                                            'Visible',                          'off',...
                                            'CellSelectionCallback',    @hTable_SS_Callback);
                                        
jscroll_hTable_PL = findjobj(hTable.PL);

% CB Date Table
hTable.CBDate = uitable('parent',                        hPanel.Table,...
                                   'Units',                          'normalized', ...
                                   'Position',                      [0 0.5 1 0.5],...
                                   'ForegroundColor',         [1 1 1],...
                                   'BackgroundColor',         [0 0 0],...
                                    'ColumnName',             [],...
                                    'Columnwidth',             {100},...
                                    'ColumnFormat',           {'char'},...
                                    'RowName',                  [],...
                                    'FontSize',                     10,....
                                    'Visible',                      'off', ...
                                    'CellSelectionCallback',  @hTable_CBDate_Callback);
                 
jscroll_hTable_CBDate = findjobj(hTable.CBDate);

%% View panel
hPanel.View = uipanel('Parent',                    hFig,...    
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'Position',                  [0.1 0 0.9 1],...
                                'ForegroundColor',       'white',...
                                'BackgroundColor',       'black',...
                                             'HighlightColor',          'black',...
                                             'ShadowColor',            'black',...
                                'Visible',                     'off');
                            
Param.CT.pos = [0 0 0.6 1
                         0.6 0.5 0.4 0.5
                         0.6 0.0 0.4 0.5];

Param.CT.Text{1} = 'Axial slice:';
Param.CT.Text{2} = 'Sagittal slice:';
Param.CT.Text{3} = 'Coronal slice:';
Param.CTcm.Text{1} = 'Y:';
Param.CTcm.Text{2} = 'X:';
Param.CTcm.Text{3} = 'Z:';

Param.CT.tag = {'1', '2', '3'};

Param.CT.icon{1} = 'xmy.png';
Param.CT.icon{2} = 'yz.png';
Param.CT.icon{3} = 'xz.png';

% I{1} = imread('saturn.png');
% I{2} = imread('kobi.png');
% I{3} = imread('peppers.png');
% I{4} = imread('cameraman.tif');

for n = 1:3
    hPanel.CT(n) = uipanel(  'Parent',             hPanel.View,...
                                            'FontSize',                 12,...
                                             'TitlePosition',           'lefttop',...
                                            'Units',                      'normalized', ...
                                            'Position',                 Param.CT.pos(n, :),...
                                             'ForegroundColor',     'white',...
                                             'BackgroundColor',     'black', ...
                                             'HighlightColor',          'black',...
                                             'ShadowColor',            'black',...
                                             'tag',      Param.CT.tag{n});
                                         %,...
%                                              'BorderType',              'etchedout',...
%                                              'BorderWidth',             2);
 %                                          'Title',                        Param.CT.TT{n},...
                                          
    hPushbutton.switchWin(n) = uicontrol('parent',   hPanel.CT(n),...
                                                'Style',    'pushbutton',...
                                                'String',    'O', ...
                                                'Units',     'normalized', ...
                                                'FontSize', 10, ...
                                               'Position', [0.97 0.97 0.025 0.025],...
                                                'ForegroundColor',         [1 0 0],...
                                                'BackgroundColor',         [0 0 0], ...
                                                'Tag',              Param.CT.tag{n}, ...
                                                'Callback', @hPushbutton_switchWin_Callback);

    hAxis.CT(n) = axes('Parent',                   hPanel.CT(n), ...
                                        'Units',                    'normalized', ...
                                        'Position',                 [0 0 1 1]);
                                    
    hPlotObj.CT(n) = imshow([], 'parent', hAxis.CT(n));
    
    %% icon
    hAxis.icon(n) = axes('Position', [0.9, 0. , 0.1 , 0.2], 'parent', hPanel.CT(n));
    L = imread(Param.CT.icon{n});
    imshow(L, 'parent', hAxis.icon(n));

    
    %% Text
    hText.CT(n) = uicontrol('parent',       hPanel.CT(n),...
                                    'Style',         'text',...
                                    'Units',          'normalized', ...
                                    'Position',      [0.6 0. 0.3 0.05],...
                                    'String',          Param.CT.Text{n},...
                                     'BackgroundColor', [0 0 0],...             
                                     'ForegroundColor', 'cyan',...
                                     'FontSize', 12, ...
                                      'FontWeight', 'bold', ...
                                      'Visible', 'off');

    hText.CTcm(n) = uicontrol('parent',       hPanel.CT(n),...
                                    'Style',         'text',...
                                    'Units',          'normalized', ...
                                    'Position',      [0.1 0 0.3 0.05],...
                                    'String',          Param.CTcm.Text{n},...
                                     'BackgroundColor', [0 0 0],...             
                                     'ForegroundColor', 'red',...
                                     'FontSize', 12, ...
                                      'FontWeight', 'bold', ...
                                      'Visible', 'off');

end
set(hPlotObj.CT, 'ButtonDownFcn', @ibdcb); % ImageButtonDownCallBack
Param.CT.singleWin = false;

%% SS
hPlotObj.SS.z = line(hAxis.CT(1), 'XData', [], 'YData', [], 'LineStyle', 'none', 'Marker', '.');
hPlotObj.SS.x = line(hAxis.CT(2), 'XData', [], 'YData', [], 'LineStyle', 'none', 'Marker', '.');
hPlotObj.SS.y = line(hAxis.CT(3), 'XData', [], 'YData', [], 'LineStyle', 'none', 'Marker', '.');

%% iso
hPlotObj.iso.z = line((nan), (nan), 'Marker', '+', 'MarkerSize', 50,  'Color','yellow', 'parent', hAxis.CT(1));
hPlotObj.iso.x = line((nan), (nan), 'Marker', '+', 'MarkerSize', 50,  'Color','yellow', 'parent', hAxis.CT(2));
hPlotObj.iso.y = line((nan), (nan), 'Marker', '+', 'MarkerSize', 50,  'Color','yellow', 'parent', hAxis.CT(3));

%% cross line
hPlotObj.CrossLine.z(1) = line(hAxis.CT(2), 'XData', [], 'YData', []);
hPlotObj.CrossLine.z(2) = line(hAxis.CT(3), 'XData', [], 'YData', []);
hPlotObj.CrossLine.x(1) = line(hAxis.CT(1), 'XData', [], 'YData', []);
hPlotObj.CrossLine.x(2) = line(hAxis.CT(3), 'XData', [], 'YData', []);
hPlotObj.CrossLine.y(1) = line(hAxis.CT(1), 'XData', [], 'YData', []);
hPlotObj.CrossLine.y(2) = line(hAxis.CT(2), 'XData', [], 'YData', []);

set(hPlotObj.CrossLine.z, 'color', 'cyan', 'visible', 'off')
set(hPlotObj.CrossLine.x, 'color', 'cyan', 'visible', 'off')
set(hPlotObj.CrossLine.y, 'color', 'cyan', 'visible', 'off')

%% Contrast Bar panel
hPanel.Bar = uipanel('Parent',                    hFig,...    
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'Position',                  [0.1 0 0.04 0.5],...
                                'ForegroundColor',       'white',...
                                'BackgroundColor',       'black', ...
                                'HighlightColor',          'black',...
                                'ShadowColor',            'black');

[hAxis_bar] = addContrastBar(hFig, hPanel.Bar);
hAxis.contrast1 = hAxis_bar.contrast1;
hAxis.contrast2 = hAxis_bar.contrast2;
