function [hPanel, hTable, hPushbutton, hAxis, hPlotObj, hText, Param] = addPanel(hFig)

%% Patient List panel
hPanel.PL = uipanel('Parent',                    hFig,...    
                             'Title',                        'Patient List',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'Position',                  [0 0 0.1 1],...
                                    'visible',                      'off', ...
                                'ForegroundColor',       'white',...
                                'BackgroundColor',       'black', ...
                                'HighlightColor',          'cyan',...
                                'ShadowColor',            'black');

hEditBox.pt = uicontrol('parent', hPanel.PL,...
                            'Style',  'Edit',...
                            'Units',                          'normalized', ...
                            'Position',                      [0.05 0.96 0.9 0.03],...
                                   'ForegroundColor',         [1 1 1],...
                                   'BackgroundColor',         [0 0 0],...
                            'String', '',...
                                    'FontSize',                     11, ...
                           'KeyPressFcn', @hEditBox_pt_Callback);                            
                            
hTable.PL = uitable('parent', hPanel.PL,...
                                   'Units',                          'normalized', ...
                                       'Position',                      [0 0 1 0.9],...
                                   'ForegroundColor',         [1 1 1],...
                                   'BackgroundColor',         [0 0 0],...
                                    'ColumnName',             [],...
                                    'Columnwidth',             'auto',...
                                    'ColumnFormat',           {'char'},...
                                    'RowName',                  [],...
                                    'FontSize',                     10, ...
                                    'CellSelectionCallback',  @hTable_PL_Callback);

% % Patient info                                
hPanel.ptInfo = uipanel('Parent',                    hFig,...    
                             'Title',                        'Patient Infomation',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'Position',                  [0 0.75 0.15 0.25],...
                                    'visible',                      'off', ...
                                'ForegroundColor',       'white',...
                                'BackgroundColor',       'black', ...
                                'HighlightColor',          'cyan',...
                                'ShadowColor',            'black');

hTable.ptInfo = uitable('parent',                       hPanel.ptInfo,...
                                   'Units',                          'normalized', ...
                                   'Position',                      [0 0 1 1],...
                                   'ForegroundColor',         [1 1 1],...
                                   'BackgroundColor',         [0 0 0],...
                                    'ColumnName',             [],...
                                    'Columnwidth',             'auto',...
                                    'ColumnFormat',           {'char'},...
                                    'RowName',                  {'RadoncID', 'Last Name', 'First Name', 'Gender', 'DOB'},...
                                    'FontSize',                     10);

% Patient selection                              
hPushbutton.ptSelection = uicontrol('parent',   hPanel.PL,...
                                                'Style',    'pushbutton',...
                                                'String',    'Load', ...
                                                'Units',     'normalized', ...
                                                'FontSize', 10, ...
                                               'Position', [0.1 0.91 0.8 0.03],...
                                                'ForegroundColor',         [0 1 0],...
                                                'BackgroundColor',         [0 0 0],...
                                                'Callback', @hPushbutton_ptSelection_Callback);

%% Structture List Panel                                           
hPanel.SS = uipanel('Parent',                    hFig,...    
                             'Title',                        'Structure',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'Position',                  [0 0 0.1 0.5],...
                                            'Visible',                          'off',...
                                'ForegroundColor',       'white',...
                                'BackgroundColor',       'black', ...
                                'HighlightColor',          'cyan',...
                                'ShadowColor',            'black');

ColumnName =  [];
RowName = [];

hTable.SS = uitable('parent', hPanel.SS,...
                                           'Units', 'normalized', ...
                                           'Position', [0 0 1 1],...
                                             'ForegroundColor',         [1 1 1],...
                                            'BackgroundColor',         [0 0 0],...
                                            'ColumnName',               ColumnName,...
                                            'Columnwidth',                {25 175},...
                                            'ColumnFormat',             {'logical', 'char'},...
                                            'ColumnEditable',            [true false], ...
                                            'RowName',                     RowName,...
                                            'FontSize',                       10,....
                                            'CellSelectionCallback',    @hTable_SS_Callback);
                                        
%% CB Date Panel
hPanel.CBDate = uipanel('Parent',                    hFig,...    
                             'Title',                        'Cone Beam Date',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'Position',                  [0 0.5 0.1 0.5],...
                                    'Visible',                      'off', ...
                                'ForegroundColor',       'white',...
                                'BackgroundColor',       'black', ...
                                'HighlightColor',          'cyan',...
                                'ShadowColor',            'black');

hTable.CBDate = uitable('parent',                        hPanel.CBDate,...
                                   'Units',                          'normalized', ...
                                   'Position',                      [0 0 1 1],...
                                   'ForegroundColor',         [1 1 1],...
                                   'BackgroundColor',         [0 0 0],...
                                    'ColumnName',             [],...
                                    'Columnwidth',             {100},...
                                    'ColumnFormat',           {'char'},...
                                    'RowName',                  [],...
                                    'FontSize',                     10,....
                                    'CellSelectionCallback',  @hTable_CBDate_Callback);
                 
jscroll_hTable_CBDate = findjobj(hTable.CBDate);

%% View panel
hPanel.View = uipanel('Parent',                    hFig,...    
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'Position',                  [0.1 0 0.9 1],...
                                'ForegroundColor',       'white',...
                                'BackgroundColor',       'black',...
                                             'HighlightColor',          'black',...
                                             'ShadowColor',            'black',...
                                'Visible',                     'off');

%% CT panel (inside View panel)                            
Param.CT.pos = [0 0 0.6 1
                         0.6 0.5 0.4 0.5
                         0.6 0.0 0.4 0.5];

Param.CT.Text{1} = 'Axial slice:';
Param.CT.Text{2} = 'Sagittal slice:';
Param.CT.Text{3} = 'Coronal slice:';
Param.CTcm.Text{1} = 'Y:';
Param.CTcm.Text{2} = 'X:';
Param.CTcm.Text{3} = 'Z:';

Param.CT.tag = {'1', '2', '3'};

Param.CT.icon{1} = 'xmy.png';
Param.CT.icon{2} = 'yz.png';
Param.CT.icon{3} = 'xz.png';

% I{1} = imread('saturn.png');
% I{2} = imread('kobi.png');
% I{3} = imread('peppers.png');
% I{4} = imread('cameraman.tif');

for n = 1:3
    hPanel.CT(n) = uipanel(  'Parent',             hPanel.View,...
                                            'FontSize',                 12,...
                                             'TitlePosition',           'lefttop',...
                                            'Units',                      'normalized', ...
                                            'Position',                 Param.CT.pos(n, :),...
                                             'ForegroundColor',     'white',...
                                             'BackgroundColor',     'black', ...
                                             'HighlightColor',          'black',...
                                             'ShadowColor',            'black',...
                                             'tag',      Param.CT.tag{n});
                                         %,...
%                                              'BorderType',              'etchedout',...
%                                              'BorderWidth',             2);
 %                                          'Title',                        Param.CT.TT{n},...
                                          
    hPushbutton.switchWin(n) = uicontrol('parent',   hPanel.CT(n),...
                                                'Style',    'pushbutton',...
                                                'String',    'O', ...
                                                'Units',     'normalized', ...
                                                'FontSize', 10, ...
                                               'Position', [0.97 0.97 0.025 0.025],...
                                                'ForegroundColor',         [1 0 0],...
                                                'BackgroundColor',         [0 0 0], ...
                                                'Tag',              Param.CT.tag{n}, ...
                                                'Callback', @hPushbutton_switchWin_Callback);

    hAxis.CT(n) = axes('Parent',                   hPanel.CT(n), ...
                                        'Units',                    'normalized', ...
                                        'Position',                 [0 0 1 1]);
                                    
    hPlotObj.CT(n) = imshow([], 'parent', hAxis.CT(n));
    
    % icon
    hAxis.icon(n) = axes('Position', [0.9, 0. , 0.1 , 0.2], 'parent', hPanel.CT(n));
    L = imread(Param.CT.icon{n});
    imshow(L, 'parent', hAxis.icon(n));

    
    % Text
    hText.CT(n) = uicontrol('parent',       hPanel.CT(n),...
                                    'Style',         'text',...
                                    'Units',          'normalized', ...
                                    'Position',      [0.6 0. 0.3 0.05],...
                                    'String',          Param.CT.Text{n},...
                                     'BackgroundColor', [0 0 0],...             
                                     'ForegroundColor', 'cyan',...
                                     'FontSize', 12, ...
                                      'FontWeight', 'bold', ...
                                      'Visible', 'off');

    hText.CTcm(n) = uicontrol('parent',       hPanel.CT(n),...
                                    'Style',         'text',...
                                    'Units',          'normalized', ...
                                    'Position',      [0.1 0 0.3 0.05],...
                                    'String',          Param.CTcm.Text{n},...
                                     'BackgroundColor', [0 0 0],...             
                                     'ForegroundColor', 'red',...
                                     'FontSize', 12, ...
                                      'FontWeight', 'bold', ...
                                      'Visible', 'off');

end
set(hPlotObj.CT, 'ButtonDownFcn', @ibdcb); % ImageButtonDownCallBack
Param.CT.singleWin = false;

% SS init.
hPlotObj.SS.z = line(hAxis.CT(1), 'XData', [], 'YData', [], 'LineStyle', 'none', 'Marker', '.');
hPlotObj.SS.x = line(hAxis.CT(2), 'XData', [], 'YData', [], 'LineStyle', 'none', 'Marker', '.');
hPlotObj.SS.y = line(hAxis.CT(3), 'XData', [], 'YData', [], 'LineStyle', 'none', 'Marker', '.');

% iso init
hPlotObj.iso.z = line((nan), (nan), 'Marker', '+', 'MarkerSize', 50,  'Color','yellow', 'parent', hAxis.CT(1));
hPlotObj.iso.x = line((nan), (nan), 'Marker', '+', 'MarkerSize', 50,  'Color','yellow', 'parent', hAxis.CT(2));
hPlotObj.iso.y = line((nan), (nan), 'Marker', '+', 'MarkerSize', 50,  'Color','yellow', 'parent', hAxis.CT(3));

% cross line init
hPlotObj.CrossLine.z(1) = line(hAxis.CT(2), 'XData', [], 'YData', []);
hPlotObj.CrossLine.z(2) = line(hAxis.CT(3), 'XData', [], 'YData', []);
hPlotObj.CrossLine.x(1) = line(hAxis.CT(1), 'XData', [], 'YData', []);
hPlotObj.CrossLine.x(2) = line(hAxis.CT(3), 'XData', [], 'YData', []);
hPlotObj.CrossLine.y(1) = line(hAxis.CT(1), 'XData', [], 'YData', []);
hPlotObj.CrossLine.y(2) = line(hAxis.CT(2), 'XData', [], 'YData', []);

set(hPlotObj.CrossLine.z, 'color', 'cyan', 'visible', 'off')
set(hPlotObj.CrossLine.x, 'color', 'cyan', 'visible', 'off')
set(hPlotObj.CrossLine.y, 'color', 'cyan', 'visible', 'off')

%% pdf Panel
hPanel.pdf_zTime = uipanel(  'Parent',             hPanel.View,...
                                   'Title',                'pdf (Axial)',...
                                             'FontSize',                 12,...
                                             'TitlePosition',           'centertop',...
                                            'Units',                      'normalized', ...
                                            'Position',                 [0. 0.5 1/3 0.5],...
                                             'ForegroundColor',     'white',...
                                             'BackgroundColor',     'black', ...
                                             'HighlightColor',          'cyan',...
                                             'ShadowColor',            'black',...
                                             'Visible',                     'off');

ySub = 0.5;
hSub = 0.5;
nSub = 4;
for iSub = 1:nSub
    xSub = (iSub-1)/nSub;
    wSub = 1/nSub;
    
    hAxis.sliceSub(iSub) = axes(   'parent',    hPanel.pdf_zTime, ...
                                                'Units',      'normalized', ...
                                                'Position',   [xSub ySub wSub hSub]);
                                            
    hPlotObj.sliceSub(iSub) = imshow([], 'parent', hAxis.sliceSub(iSub));
    hPlotObj.isoSub(iSub).z = line((nan), (nan), 'Marker', '+', 'MarkerSize', 50,  'Color','yellow', 'parent', hAxis.sliceSub(iSub));

    hAxis.histSub(iSub) = axes(   'parent',    hPanel.pdf_zTime, ...
                                                'Units',      'normalized', ...
                                                'Position',   [xSub 0.05 wSub ySub-0.1]);

    set(hAxis.histSub(iSub), 'Color', 'k'); 
    axis(hAxis.histSub(iSub), 'off');

    hPlotObj.subPDF(iSub).CB1 = line(hAxis.histSub(iSub), 'XData', [], 'YData', [], 'Color', 'm', 'linewidth', 2);
    hPlotObj.subPDF(iSub).CB = line(hAxis.histSub(iSub), 'XData', [], 'YData', [], 'Color', 'g', 'linewidth', 2);

end                                         

%% metrics Panel Time
hPanel.Stat_zTime = uipanel(  'Parent',             hPanel.View,...
                                             'FontSize',                 12,...
                                             'TitlePosition',           'centertop',...
                                            'Units',                      'normalized', ...
                                            'Position',                 [1/3 0.5 2/3 0.5],...
                                             'ForegroundColor',     'white',...
                                             'BackgroundColor',     'black', ...
                                             'HighlightColor',          'cyan',...
                                             'ShadowColor',            'black',...
                                             'Visible',                     'off');
%                                               'Title',                'Metrics',...

hstatTabGroup = uitabgroup('Parent', hPanel.Stat_zTime);
    
titleName{1} = 'Mean Square Error';
titleName{2} = 'Correlation Coefficient';
titleName{3} = 'Mutual Information';
titleName{4} = 'Feature Similarity';
titleName{5} = 'Area Delta';
titleName{6} = 'Morph Delta';
    

for iT = 1:length(titleName)
    hStatTab_zTime(iT) = uitab('Parent', hstatTabGroup, 'Title', titleName{iT});
    set(hStatTab_zTime(iT), 'Backgroundcolor', 'k')

    % add axes for 2d
    hAxis.Stat_zTime2d(iT) = axes('Parent',                   hStatTab_zTime(iT), ...
                                    'color',        'k',...
                                    'xcolor', 'w',...
                                    'ycolor', 'w', ...
                                    'gridcolor',   'w',...
                                    'Units',                    'normalized', ...
                                    'HandleVisibility',     'callback', ...
                                    'Position',                 [0.05 0.15 0.45 0.75]);
                                
    hPlotObj.Stat_zTime2d(iT) = line(hAxis.Stat_zTime2d(iT), 'XData', [], 'YData', [],...
                                    'Marker', '.',  'MarkerSize', 36);
                                
    hPlotObj.StatSub_zTime2d(iT) = line(hAxis.Stat_zTime2d(iT), 'XData', [], 'YData', [],...
                                    'Color', 'none', 'Marker', '.', 'MarkerSize', 36); 
                                    
    % add axes for 3d
    hAxis.Stat_zTime3d(iT) = axes('parent',        hStatTab_zTime(iT),...
                                                'Color',         'k',...
                                                'xcolor',    'w',...
                                                'ycolor',    'w', ...
                                                'zcolor',    'w', ...
                                                'Units',                    'normalized', ...
                                                'HandleVisibility',     'callback', ...
                                                'Position',     [0.525 0.15 0.425 0.75]);
                                                
                                                
    if ismember(iT, [2 3 4])
        set(hAxis.Stat_zTime2d(iT),'Ydir','reverse')
        set(hAxis.Stat_zTime3d(iT),'Zdir','reverse')
    end
end
                                         
%% Contrast Bar panel
hPanel.Bar = uipanel('Parent',                    hPanel.CT(1),...    
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'Position',                  [0 0.1 0.1 0.8],...
                                'ForegroundColor',       'white',...
                                'BackgroundColor',       'black', ...
                                'HighlightColor',          'black',...
                                'ShadowColor',            'black');

[hAxis_bar] = addContrastBar(hFig, hPanel.Bar);
hAxis.contrast1 = hAxis_bar.contrast1;
hAxis.contrast2 = hAxis_bar.contrast2;

%% CB info panel
hPanel.CBInfo = uipanel('Parent',                    hFig,...    
                                'Title',                      'Cone Beam Information',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'Position',                  [0.1 0.5 0.9 0.5],...
                                'ForegroundColor',       'white',...
                                'BackgroundColor',       'black',...
                                             'HighlightColor',          'cyan',...
                                             'ShadowColor',            'black',...
                                'Visible',                     'off');

